"""Build-time gate: verify every entity that could surface a purple
Source link in the viewer has at least one cited source-id resolving
to a registered + URL-live entry in schema/sources.yaml.

Pass A (structural):  every cited source-id is in registry, with url + apa
Pass B (URL liveness): every entity has at least one source whose url
                       is not in the known-dead set
                       (tools/_dead_url_sources.txt — manually maintained,
                        regenerated by tools/url_health_sweep.py)

Exit code 0 = clean (publish-safe); 1 = one or more gaps (publish-unsafe).
Run via:   python tools/verify_source_coverage.py
Wired into tools/build-graph.py so a build is rejected if coverage breaks.
"""
import yaml, glob, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEAD_FILE = os.path.join(ROOT, 'tools', '_dead_url_sources.txt')

def parse_md(fp):
    try:
        with open(fp, 'r', encoding='utf-8') as f: txt = f.read()
        if not txt.startswith('---'): return None
        end = txt.find('---', 3)
        return yaml.safe_load(txt[3:end])
    except Exception: return None

def load_registry():
    with open(os.path.join(ROOT, 'schema', 'sources.yaml'), 'r', encoding='utf-8') as f:
        return {s['id']: s for s in yaml.safe_load(f)['sources'] if s.get('id')}

def load_dead_set():
    if not os.path.exists(DEAD_FILE): return set()
    with open(DEAD_FILE, 'r', encoding='utf-8') as f:
        return set(line.strip() for line in f if line.strip() and not line.startswith('#'))

def verify(strict=False):
    """Return (ok, gaps_dict). strict=True applies Pass B; otherwise Pass A only."""
    registry = load_registry()
    bar_a    = {sid: s for sid, s in registry.items() if s.get('url') and s.get('apa')}
    dead     = load_dead_set() if strict else set()
    bar_b    = {sid: s for sid, s in bar_a.items() if sid not in dead}
    target   = bar_b if strict else bar_a
    gaps = {'artifact': [], 'concept': [], 'convergence': [], 'convergence_join_chain': [], 'scenario_step': []}

    def passes(sids):
        return any(sid in target for sid in (sids or []))

    for fp in glob.glob(os.path.join(ROOT, 'artifacts', '**', '*.md'), recursive=True):
        fm = parse_md(fp)
        if not fm: continue
        if not passes(fm.get('provenance')):
            gaps['artifact'].append(fm.get('name', os.path.basename(fp)))

    for fp in glob.glob(os.path.join(ROOT, 'concepts', '*.md')):
        fm = parse_md(fp)
        if not fm: continue
        if not passes(fm.get('provenance')):
            gaps['concept'].append(fm.get('name', os.path.basename(fp)))

    for fp in glob.glob(os.path.join(ROOT, 'convergences', '*.md')):
        fm = parse_md(fp)
        if not fm: continue
        name = fm.get('name', os.path.basename(fp))
        if not passes(fm.get('provenance')):
            gaps['convergence'].append(name)
        for jc in (fm.get('join-chain') or []):
            ps = jc.get('primary-source')
            srcs = (jc.get('sources') or [])
            if not passes(([ps] if ps else []) + srcs):
                gaps['convergence_join_chain'].append(name + '/' + jc.get('concept', '?'))

    for fp in glob.glob(os.path.join(ROOT, 'scenarios', '*.md')):
        fm = parse_md(fp)
        if not fm: continue
        name = fm.get('name', os.path.basename(fp))
        for s in (fm.get('steps') or []):
            ps = s.get('primary-source')
            if not ps or ps not in target:
                gaps['scenario_step'].append(name + ' step ' + str(s.get('n', '?')))

    total = sum(len(v) for v in gaps.values())
    return (total == 0), gaps

def main():
    strict = '--strict' in sys.argv
    bar = 'B (URL-live)' if strict else 'A (structural)'
    print('Source coverage verification — Bar ' + bar)
    ok, gaps = verify(strict=strict)
    if ok:
        print('[OK] All entities have at least one source meeting Bar ' + bar + '.')
        sys.exit(0)
    print('[FAIL] Coverage gaps:')
    for cat, items in gaps.items():
        if not items: continue
        print('  -- ' + cat + ' (' + str(len(items)) + ') --')
        for it in items[:8]:
            print('     ' + it)
        if len(items) > 8:
            print('     ... and ' + str(len(items) - 8) + ' more')
    sys.exit(1)

if __name__ == '__main__':
    main()
